export const siteCopy = {
  brand: "12 MINUTES TO FREEDOM",
  buy: "Buy the Book",
  footerIntro: "A thriller by Todd Shevlin.",
  publisher: "Published by Collingwood Press",
  copyright: "Todd Shevlin. All rights reserved.",
  privacy: "Privacy Policy",
  cookies: "Cookie Policy",
  cookieSettings: "Cookie Settings",
  signup: {
    label: "Email address", placeholder: "Your email address", send: "Send Me Chapter Two",
    consent: "One email with your free chapters, then occasional news from Todd. Unsubscribe anytime.",
    success: "Check your inbox. Chapter Two is on its way.",
    unavailable: "Sign-up is being connected. Please try again soon.",
  },
  modal: { title: "Choose your edition", description: "Choose a format, then choose where to buy.", formats: ["Hardcover", "Paperback", "Kindle", "Audiobook"], unavailable: "Human-narrated audiobook in production." },
  consent: { title: "Your privacy matters", body: "Essential cookies keep this site working. Choose whether to allow analytics and marketing cookies.", accept: "Accept all", reject: "Reject non-essential", customize: "Customize", save: "Save choices", analytics: "Analytics", marketing: "Marketing" },
  nav: { menu: "Open menu", close: "Close menu" },
  notFound: { title: "Case file not found.", body: "The page you are looking for is not here.", action: "Return home" },
  shells: {
    book: { title: "The Book", intro: "One man framed for murder. One crew ready to prove the truth." },
    chapter: { title: "Free Chapter", intro: "Chapter One is coming soon. For now, the clock is already ticking." },
    about: { title: "About Todd", intro: "Meet the author behind 12 Minutes to Freedom." },
    press: { title: "Press", intro: "Press information for 12 Minutes to Freedom." },
    blog: { title: "Blog", intro: "Notes on the story, the clues, and the people behind it." },
    privacy: { title: "Privacy Policy", intro: "Details about how this site handles your information will appear here." },
    cookies: { title: "Cookie Policy", intro: "Details about this site's cookies will appear here." },
  },
} as const;
